spring.config.import=optional:file:.env.properties

# Database Configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update

# Server Configuration
server.port=${SERVER_PORT}
server.address=${SERVER_HOST}

server.forward-headers-strategy=native

# File Upload Configuration
upload.payments.path=uploads/payments
upload.contracts.path=uploads/contracts
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
